#!/usr/bin/env bash
[ -n "$SHELL_SCRIPT_LIB" ] || { echo "SHELL_SCRIPT_LIB not set"; exit 1; } 			#NO_COMPILE#
# shellcheck disable=SC1090									#NO_COMPILE#
include() { . "${SHELL_SCRIPT_LIB}/${1}" || { echo "$1 not found"; exit 1; } }			#NO_COMPILE#

# this script
_PATH=$(readlink -f "$0")
_DIR=$(dirname "$_PATH")
_FILENAME=$(basename "$_PATH")

# includes
include "std"
include "validate_dir_readable"
include "validate_dir_writeable"

# requirements
command -v sha256sum > /dev/null 2>&1 || exit_error "sha256 is not installed"
command -v tar > /dev/null 2>&1 || exit_error "tar is not installed"
command -v gpg > /dev/null 2>&1 || exit_error "gpg is not installed"

# constants
DATE=$(date +"%d%m%y-%H%M")
CHECKSUM_FILE=".sha256sum"

# usage/help
USAGE="$_FILENAME -s /path/to/source/directory -d /path/to/destination/directory [-i <gpg-id>] [-p]"
HELP=$(cat <<HELP
$USAGE
-s	source directory
-d	destination directory
-i	gpg id (optional)
-p	fix permissions (file: 600, dir: 700)
HELP
)

# global vars
a_source_dir=
a_backup_dir=
a_gpg_id=
a_fix_permissions=false

# functions
read_opts() {
        while getopts "s:d:i:p" OPTS; do
                case $OPTS in
			h)	usage "$HELP";;
			s)      a_source_dir=$(readlink -f "$OPTARG");;
			d)      a_backup_dir=$(readlink -f "$OPTARG");;
			i)	a_gpg_id="$OPTARG";;
			p)	a_fix_permissions=true;;
                        \?)     usage "$USAGE"
                esac
        done

	validate_dir_readable "$a_source_dir" || exit_error "source dir does not exist or is not readable"
	validate_dir_writeable "$a_backup_dir" || exit_error "destination dir does not exist or is not writeable"

	if [ -n "$a_gpg_id" ]; then
		gpg --list-keys "$a_gpg_id" &> /dev/null || exit_error "gpg id does not exist"
	fi
}

fix_permissions() {
	echo "# fixing permissions"
	find "$a_source_dir" -type d -not -perm 700 -exec chmod 700 {} \;
	find "$a_source_dir" -type f -not -perm 600 -exec chmod 600 {} \;
}

is_different_checksum() {
	echo "# checking checksum"
	local checksum_path="${a_source_dir}/${CHECKSUM_FILE}"
	local checksum=$(tar -P --exclude="$checksum_path" -cf - "$a_source_dir" | sha256sum | head -c 64)

	if [ -f "$checksum_path" ]; then
		old_checksum=$(cat "$checksum_path" | head -c 64)

		if [ "$checksum" = "$old_checksum" ]; then
			echo "# $a_source_dir did not change"
			return 1
		else 
			echo "# $a_source_dir changed"
			echo $checksum > "${checksum_path}"
			return 0
		fi
	else
		echo "# writing new checksum"	
		echo $checksum > "${checksum_path}"
	fi
}

encrypt_archive() {
	local archive_path="$1"
	local encrypted_archive_path="${archive_path}.gpg"

	echo "# encrypting archive"
	gpg --batch --yes -e -r "$a_gpg_id" "$archive_path"
	chmod 600 "${encrypted_archive_path}"
	rm "${archive_path}"
}

create_archive() {
	local source_parent_dir=$(dirname "$a_source_dir")
	local source_base_dir=$(basename "$a_source_dir")

	local archive_file="${source_base_dir}-${DATE}.tgz"
	if [ "${archive_file:0:1}" = "." ]; then 	# fix archive name if it is hidden
		archive_file="${archive_file:1}"
	fi
	local archive_path="${a_backup_dir}/${archive_file}"

	echo "# creating archive"
	tar cfz "${archive_path}" -C "$source_parent_dir" $source_base_dir
	chmod 600 "${archive_path}"

	if [ -n "$a_gpg_id" ]; then
		encrypt_archive "${archive_path}"
	fi
}

# main
read_opts "$@"

if $a_fix_permissions; then
	fix_permissions
fi

if is_different_checksum; then
	create_archive
fi

exit 0
